name: Java CI with Maven on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Change from macOS to Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Chrome
        run: |
          choco install googlechrome --no-progress  # Use Chocolatey to install Chrome on Windows

      - name: Install ChromeDriver
        run: |
          choco install chromedriver --no-progress  # Install ChromeDriver on Windows

      - name: Build with Maven
        run: mvn clean install -e

      - name: Run with Maven
        run: mvn clean test
